url: "https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives_en?page="
chrome_settings:
  - "--window-size=1920,1080"
  - "start-maximized"
  - "headless"
webdriver_wait:
  timeout: 10
dev_settings: "on" #can be on or off