url: "https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives_en?page="
xpath:
  links: "//a[@class=\"ecl-u-pt-xs ecl-u-type-none\"]"
  page_numbers: "//*[@id=\"ecl-main-content\"]/div/ng-component/div/section/ux-block-content/div/app-pagination/ecl-pagination/nav/ul/ecl-pagination-item[6]/a"
chrome_settings:
  - "--window-size=1920,1080"
  - "start-maximized"
  - "headless"
webdriver_wait:
  timeout: 10